---
output: 
  html_document: 
    fig_caption: yes
    keep_md: yes
params: 
  language: EN  # either "EN", "FR", or "AR"
---

```{r preamble, echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r translation}
load("translation.RData")
```

# `r translation[1, params$language]`

## `r translation[2, params$language]`

`r translation[3, params$language]`

## `r translation[4, params$language]`

`r translation[7, params$language]`

`r translation[8, params$language]`

`r translation[9, params$language]`

`r translation[10, params$language]`

`r translation[11, params$language]`

### `r translation[12, params$language]`

`r translation[13, params$language]`

```{r target1-1, message=FALSE, warning=FALSE}
library(dplyr)
library(ggplot2)
library(artyfarty)
library(plotly)
load('data/households_worldwide.RData')
ggplot(households_worldwide) + 
  geom_col( aes(x = year, y = households, fill="#000099") ) +
  theme_economist() +
    ggtitle(as.character(translation[14, params$language])) +
    xlab( as.character(translation[15, params$language]) ) +
    ylab( as.character(translation[16, params$language]) ) +
    scale_fill_manual(values = pal("economist")) +
    theme(legend.position='none') -> households_plot
ggplotly(households_plot) %>% config(displayModeBar = FALSE)
```